# Generated by Django 4.1 on 2022-09-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocIdentidad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=15)),
                ('creacion', models.DateTimeField()),
                ('actualizacion', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Documentos de identidad',
                'db_table': 'doc_identidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=15)),
                ('creacion', models.DateTimeField()),
                ('actualizacion', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Estados civiles',
                'db_table': 'estado_civil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BooleanField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=15)),
                ('creacion', models.DateTimeField()),
                ('actualizacion', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Generos',
                'db_table': 'genero',
                'managed': False,
            },
        ),
    ]
