# Generated by Django 4.1.3 on 2022-12-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='id_tip',
            field=models.ForeignKey(db_column='id_tip', on_delete=django.db.models.deletion.DO_NOTHING, to='business.tipomulta'),
        ),
        migrations.AddField(
            model_name='galeriainterior',
            name='id_viv',
            field=models.ForeignKey(db_column='id_viv', on_delete=django.db.models.deletion.DO_NOTHING, to='business.vivienda'),
        ),
        migrations.AddField(
            model_name='galeriaexterior',
            name='id_viv',
            field=models.ForeignKey(db_column='id_viv', on_delete=django.db.models.deletion.DO_NOTHING, to='business.vivienda'),
        ),
        migrations.AddField(
            model_name='detallemulta',
            name='id_che',
            field=models.ForeignKey(db_column='id_che', on_delete=django.db.models.deletion.DO_NOTHING, to='business.checkout'),
        ),
        migrations.AddField(
            model_name='detallemulta',
            name='id_mul',
            field=models.ForeignKey(db_column='id_mul', on_delete=django.db.models.deletion.DO_NOTHING, to='base.multa'),
        ),
    ]
