# Generated by Django 4.1.3 on 2022-12-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('base', '0002_initial'),
        ('users', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='id_cli',
            field=models.OneToOneField(db_column='id_cli', on_delete=django.db.models.deletion.DO_NOTHING, to='users.clicom'),
        ),
        migrations.AddField(
            model_name='cliacom',
            name='id_aco',
            field=models.ForeignKey(db_column='id_aco', on_delete=django.db.models.deletion.DO_NOTHING, to='people.acompaniante'),
        ),
        migrations.AddField(
            model_name='cliacom',
            name='id_cli',
            field=models.ForeignKey(db_column='id_cli', on_delete=django.db.models.deletion.DO_NOTHING, to='people.cliente'),
        ),
        migrations.AddField(
            model_name='cliacom',
            name='id_res',
            field=models.ForeignKey(db_column='id_res', on_delete=django.db.models.deletion.DO_NOTHING, to='business.reserva'),
        ),
    ]
