# Generated by Django 4.1.3 on 2022-11-24 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='ACTIVO', max_length=15)),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cvv', models.CharField(max_length=3)),
                ('fecha_expiracion', models.CharField(max_length=5)),
                ('nombre_titular', models.CharField(max_length=200)),
                ('numero_cuenta', models.CharField(max_length=100, unique=True)),
                ('persona_id', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.DO_NOTHING, to='people.persona')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'db_table': 'cuenta_bancaria',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
