# Generated by Django 4.1 on 2022-08-24 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=15)),
                ('creacion', models.DateTimeField()),
                ('actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=15)),
                ('creacion', models.DateTimeField()),
                ('actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'estado_civil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPais',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=15)),
                ('creacion', models.DateTimeField()),
                ('actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'estado_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BooleanField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=15)),
                ('creacion', models.DateTimeField()),
                ('actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdentidadDoc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=15)),
                ('creacion', models.DateTimeField()),
                ('actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'identidad_doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('cod_pais', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('cod_tel', models.CharField(max_length=10)),
                ('bandera', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(max_length=15)),
                ('creacion', models.DateTimeField()),
                ('actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('run', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('pasaporte', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('snombre', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_paterno', models.CharField(max_length=50)),
                ('ap_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=10)),
                ('num_calle', models.CharField(max_length=10)),
                ('calle', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=15)),
                ('creacion', models.DateTimeField()),
                ('actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'db_table': 'AUTH_USER_ROLE',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='user_profile/', verbose_name='Imagen de perfil')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.persona', verbose_name='Persona')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userrole', verbose_name='Rol Usuario')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'AUTH_USER_ACCOUNT',
            },
        ),
    ]
