# Generated by Django 4.1.3 on 2022-12-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataframe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rooms', models.TextField()),
                ('products', models.TextField()),
            ],
            options={
                'verbose_name': 'dataframe',
                'verbose_name_plural': 'dataframe',
                'db_table': 'dataframe',
                'ordering': ['id'],
            },
        ),
    ]
