CREATE OR REPLACE PACKAGE PKG_BUSINESS IS 
   PROCEDURE SP_FINE_VALUE (p_pk check_out.id%type);
   PROCEDURE SP_DF_ML;
   PROCEDURE SP_UPDATE_SCORE;
   FUNCTION FN_AVG_STARS(p_deptoid vivienda.ID%TYPE) RETURN NUMBER;
END PKG_BUSINESS;
